@startuml
    skinparam shadowing false
    
    title Pollare 
    !define table(name) class name << (T,#FFAAAA) >>

    table(polls)
    table(users)
    table(votes)
    table(roles)
    table(options)

    polls : INTEGER id
    polls : TEXT name
    polls : TEXT slug
    polls : TEXT creation_date
    polls : INTEGER security_level
    note bottom of polls 
        <b>security_level</b> controls 
        which votes will be pass.
        --
        0: Pass any vote.
        1: Pass any vote <b>from</b> 
            <b>a unique local ip address.</b>
        2: Pass any vote from 
            a unique <b>public ip address.</b>
        3: Pass any vote from
            a unique <b>account.</b>
    end note

    votes : INTEGER poll_id
    votes : INTEGER user_id
    votes : INTEGER role_id
    votes : TEXT local_ip_address
    votes : TEXT public_ip_address

    users : INTEGER id
    users : TEXT name
    users : TEXT email
    users : BINARY password 

    roles : INTEGER id
    roles : TEXT name

    options : INTEGER id
    options : INTEGER poll_id
    options : TEXT description

    options "1" -- "*" polls

    polls "1" -- "*" votes
    users "1" -- "*" votes 
    roles "1" -- "*" votes
    options "1" -- "*" votes
@enduml 